name: canadian_alternatives
description: An app to find Canadian alternatives to American products
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 